- hosts: all
  tasks:
   - name: stop container
     shell: docker container stop cryptoweb
   - name: remove container
     shell: docker container rm cryptoweb
   - name: remove docker image
     shell: docker image rmi raoshahzaib/bitcypo
   - name: create new container
     shell: docker container run -itd --name cryptoweb -p 9000:80 raoshahzaib/bitcypo
